In [1]:
import torch

# CUDA

In [2]:
x = torch.FloatTensor(1024, 10024).uniform_()
x

tensor([[0.3363, 0.5671, 0.8107,  ..., 0.8896, 0.5246, 0.5951],
        [0.5964, 0.4613, 0.6189,  ..., 0.4849, 0.4621, 0.7252],
        [0.6759, 0.4383, 0.1671,  ..., 0.5270, 0.6363, 0.1007],
        ...,
        [0.5357, 0.6522, 0.0056,  ..., 0.4093, 0.2206, 0.9231],
        [0.8596, 0.1210, 0.8762,  ..., 0.0386, 0.1046, 0.9616],
        [0.3260, 0.1452, 0.1382,  ..., 0.1238, 0.0316, 0.2313]])

In [3]:
x.is_cuda

False

In [10]:
# !pip3 install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio===0.8.1 -f https://download.pytorch.org/whl/torch_stable.html --user


Looking in links: https://download.pytorch.org/whl/torch_stable.html
  Using cached https://download.pytorch.org/whl/cu111/torchvision-0.9.1%2Bcu111-cp38-cp38-win_amd64.whl (1.9 MB)
  Using cached torchaudio-0.8.1-cp38-none-win_amd64.whl (109 kB)


In [5]:
x = x.cuda()

In [7]:
x

tensor([[0.3363, 0.5671, 0.8107,  ..., 0.8896, 0.5246, 0.5951],
        [0.5964, 0.4613, 0.6189,  ..., 0.4849, 0.4621, 0.7252],
        [0.6759, 0.4383, 0.1671,  ..., 0.5270, 0.6363, 0.1007],
        ...,
        [0.5357, 0.6522, 0.0056,  ..., 0.4093, 0.2206, 0.9231],
        [0.8596, 0.1210, 0.8762,  ..., 0.0386, 0.1046, 0.9616],
        [0.3260, 0.1452, 0.1382,  ..., 0.1238, 0.0316, 0.2313]],
       device='cuda:0')

In [9]:
x = x.cpu()
x

tensor([[0.3363, 0.5671, 0.8107,  ..., 0.8896, 0.5246, 0.5951],
        [0.5964, 0.4613, 0.6189,  ..., 0.4849, 0.4621, 0.7252],
        [0.6759, 0.4383, 0.1671,  ..., 0.5270, 0.6363, 0.1007],
        ...,
        [0.5357, 0.6522, 0.0056,  ..., 0.4093, 0.2206, 0.9231],
        [0.8596, 0.1210, 0.8762,  ..., 0.0386, 0.1046, 0.9616],
        [0.3260, 0.1452, 0.1382,  ..., 0.1238, 0.0316, 0.2313]])

In [11]:
torch.cuda.empty_cache()
device = torch.device("cuda:0")
x = x.to(device)
x

tensor([[0.3363, 0.5671, 0.8107,  ..., 0.8896, 0.5246, 0.5951],
        [0.5964, 0.4613, 0.6189,  ..., 0.4849, 0.4621, 0.7252],
        [0.6759, 0.4383, 0.1671,  ..., 0.5270, 0.6363, 0.1007],
        ...,
        [0.5357, 0.6522, 0.0056,  ..., 0.4093, 0.2206, 0.9231],
        [0.8596, 0.1210, 0.8762,  ..., 0.0386, 0.1046, 0.9616],
        [0.3260, 0.1452, 0.1382,  ..., 0.1238, 0.0316, 0.2313]],
       device='cuda:0')

In [13]:
a = torch.FloatTensor(10000, 10000).uniform_()
b = torch.FloatTensor(10000, 10000).uniform_()
c = a.cuda().mul(b.cuda()).cpu()
c

tensor([[0.0159, 0.7078, 0.0160,  ..., 0.1304, 0.4283, 0.0180],
        [0.4908, 0.6089, 0.6351,  ..., 0.4309, 0.1435, 0.1561],
        [0.4127, 0.0334, 0.0080,  ..., 0.0751, 0.2225, 0.0749],
        ...,
        [0.0751, 0.3444, 0.2069,  ..., 0.2414, 0.3061, 0.3871],
        [0.0362, 0.6413, 0.2665,  ..., 0.4081, 0.3758, 0.4295],
        [0.3842, 0.1602, 0.4448,  ..., 0.0550, 0.0504, 0.3530]])

In [14]:
x = torch.FloatTensor(5, 5, 5).uniform_()

# check for CUDA availability (NVIDIA GPU)
if torch.cuda.is_available():
    # get the CUDA device name
    device = torch.device('cuda')          # CUDA-device object
    y = torch.ones_like(x, device=device)  # create a tensor on GPU
    x = x.to(device)                       # or just `.to("cuda")`
    z = x + y
    print(z)
    # you can set the type while `.to` operation
    print(z.to("cpu", torch.double))

tensor([[[1.2077, 1.1641, 1.6498, 1.6731, 1.7573],
         [1.5903, 1.9865, 1.2188, 1.0934, 1.0907],
         [1.4835, 1.5855, 1.8310, 1.6898, 1.8902],
         [1.9632, 1.5813, 1.5807, 1.6303, 1.6547],
         [1.4467, 1.5998, 1.0949, 1.6972, 1.4468]],

        [[1.1832, 1.3024, 1.3798, 1.6606, 1.8696],
         [1.0398, 1.8778, 1.2634, 1.9877, 1.2189],
         [1.7075, 1.1148, 1.1481, 1.9320, 1.1343],
         [1.6900, 1.2840, 1.3315, 1.5270, 1.1909],
         [1.0281, 1.5195, 1.6565, 1.4536, 1.1506]],

        [[1.7819, 1.2737, 1.1762, 1.0843, 1.6962],
         [1.4396, 1.8233, 1.1537, 1.3430, 1.5479],
         [1.2826, 1.5255, 1.1636, 1.6420, 1.3605],
         [1.4987, 1.3669, 1.0670, 1.6593, 1.4031],
         [1.9546, 1.3137, 1.3199, 1.7646, 1.4491]],

        [[1.1927, 1.6799, 1.2934, 1.9645, 1.7139],
         [1.8851, 1.0395, 1.6528, 1.6762, 1.3919],
         [1.2800, 1.8468, 1.5094, 1.8077, 1.7808],
         [1.5087, 1.4051, 1.5290, 1.2276, 1.0697],
         [1.3444, 1.6740,