# BASE OPERATIONS

In [1]:
import torch
import numpy as np

*************************

In [2]:
# Создайте случайный FloatTensor размера 3x4x5
x = torch.FloatTensor(3, 4, 5)
print(x)

tensor([[[-1.0565e+02,  6.2498e-43, -4.0765e-38,  2.6064e-43,  0.0000e+00],
         [ 0.0000e+00,  2.1019e-44,  0.0000e+00, -1.0568e+02,  6.2498e-43],
         [-4.0765e-38,  2.6064e-43,  0.0000e+00,  0.0000e+00,  2.1019e-44],
         [ 0.0000e+00, -1.0993e+02,  6.2498e-43, -4.0765e-38,  2.6064e-43]],

        [[ 0.0000e+00,  0.0000e+00,  2.1019e-44,  0.0000e+00, -1.0085e+02],
         [ 6.2498e-43, -4.0765e-38,  2.6064e-43,  0.0000e+00,  0.0000e+00],
         [ 2.1019e-44,  0.0000e+00, -1.2482e-01,  6.2498e-43, -4.0765e-38],
         [ 2.6064e-43,  0.0000e+00,  0.0000e+00,  2.1019e-44,  0.0000e+00]],

        [[-9.7965e+01,  6.2498e-43, -4.0765e-38,  2.6064e-43,  0.0000e+00],
         [ 0.0000e+00,  2.1019e-44,  0.0000e+00, -3.3896e+01,  6.2498e-43],
         [-4.0765e-38,  2.6064e-43,  0.0000e+00,  0.0000e+00,  2.1019e-44],
         [ 0.0000e+00, -9.7664e+01,  6.2498e-43, -4.0765e-38,  2.6064e-43]]])


In [3]:
# Выведите его форму (shape)
x.shape, x.size()

(torch.Size([3, 4, 5]), torch.Size([3, 4, 5]))

In [4]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
b = torch.CharTensor([1, 4, 2, 2, 1])
x * b

tensor([[[-1.0565e+02,  2.4999e-42, -8.1530e-38,  5.2128e-43,  0.0000e+00],
         [ 0.0000e+00,  8.4078e-44,  0.0000e+00, -2.1136e+02,  6.2498e-43],
         [-4.0765e-38,  1.0426e-42,  0.0000e+00,  0.0000e+00,  2.1019e-44],
         [ 0.0000e+00, -4.3971e+02,  1.2500e-42, -8.1530e-38,  2.6064e-43]],

        [[ 0.0000e+00,  0.0000e+00,  4.2039e-44,  0.0000e+00, -1.0085e+02],
         [ 6.2498e-43, -1.6306e-37,  5.2128e-43,  0.0000e+00,  0.0000e+00],
         [ 2.1019e-44,  0.0000e+00, -2.4964e-01,  1.2500e-42, -4.0765e-38],
         [ 2.6064e-43,  0.0000e+00,  0.0000e+00,  4.2039e-44,  0.0000e+00]],

        [[-9.7965e+01,  2.4999e-42, -8.1530e-38,  5.2128e-43,  0.0000e+00],
         [ 0.0000e+00,  8.4078e-44,  0.0000e+00, -6.7791e+01,  6.2498e-43],
         [-4.0765e-38,  1.0426e-42,  0.0000e+00,  0.0000e+00,  2.1019e-44],
         [ 0.0000e+00, -3.9066e+02,  1.2500e-42, -8.1530e-38,  2.6064e-43]]])

In [5]:
# Приведите его к форме 6 X 10
x = x.view(6, 10)

In [6]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
z = x.mm(x.T)
z.size()

torch.Size([6, 6])

In [7]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

from torch.autograd import Variable

x = Variable(torch.FloatTensor([1]), requires_grad=True)
z = Variable(torch.FloatTensor([0.5]), requires_grad=True)
t = Variable(torch.FloatTensor([2]), requires_grad=True)

y = x**3 + z - 75*t
y.backward()
print(x.grad, z.grad, t.grad)
print(x.grad + z.grad+ t.grad)

tensor([3.]) tensor([1.]) tensor([-75.])
tensor([-71.])


In [8]:
# Создайте единичный тензор размера 5x6
x = torch.ones(5, 6)
x

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [9]:
# Переведите его в формат numpy
x = x.numpy()
x, type(x)

(array([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]], dtype=float32),
 numpy.ndarray)

## тензоры pytorch

* **torch.HalfTensor** = 16 бит, floating point
* **torch.FloatTensor**  = 32 бита, floating point
* **torch.DoubleTensor**  =    64 бита, floating point
* **torch.ShortTensor**    =   16 бит, integer, signed
* **torch.IntTensor**      =   32 бита, integer, signed
* **torch.LongTensor**   =      64 бита, integer, signed

* **torch.CharTensor**    =  8 бит, integer, signed
* **torch.ByteTensor**     = 8 бит, integer, unsigned

In [10]:
# Создание тензора
a = torch.FloatTensor([1, 2])
b = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])

print(a, a.shape)
print(b, b.shape)

tensor([1., 2.]) torch.Size([2])
tensor([[1., 2., 3.],
        [4., 5., 6.]]) torch.Size([2, 3])


In [11]:
# создание тензора по размерам (заполнен случайными величинами (мусором))
x = torch.FloatTensor(2, 3, 4)
print(x, x.shape)

tensor([[[1.0564e-05, 4.1880e-11, 4.3684e-05, 2.9571e-18],
         [6.7333e+22, 1.7591e+22, 1.7184e+25, 4.3222e+27],
         [6.1972e-04, 7.2443e+22, 1.7728e+28, 7.0367e+22]],

        [[9.6695e-06, 8.3101e+20, 1.3028e-11, 1.7186e-04],
         [1.0489e-08, 8.1919e-10, 1.9968e+20, 1.1038e-05],
         [3.3209e-09, 3.1199e-18, 7.7052e+31, 1.9447e+31]]]) torch.Size([2, 3, 4])


In [12]:
x = torch.IntTensor(3, 3, 4)
print(x, x.shape)

tensor([[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]], dtype=torch.int32) torch.Size([3, 3, 4])


In [13]:
# заполнение 0
x1 = torch.FloatTensor(3, 2, 4)
x1.zero_()
x2 = torch.zeros(3, 2, 4)
x3 = torch.zeros_like(x1)

assert torch.allclose(x1, x2) and torch.allclose(x1, x3)
x1

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [14]:
# случайные распределения

x = torch.randn((2, 3))
print('Стандартное Нормальное распределение: ', x, sep='\n')
x.random_(0, 10)
print('Дискретное распределение: ', x, sep='\n')
x.uniform_(0, 1)
print('Равномерное распределение: ', x, sep='\n')
x.normal_(mean=0, std=1)
print('Нормальное распределение: ', x, sep='\n')
x.bernoulli_(p=0.5)
print('Распределение Бернулли: ', x, sep='\n')

Стандартное Нормальное распределение: 
tensor([[-0.0492, -1.2892,  0.0702],
        [ 1.6328, -2.2271, -0.5642]])
Дискретное распределение: 
tensor([[2., 7., 1.],
        [8., 0., 4.]])
Равномерное распределение: 
tensor([[0.0054, 0.1482, 0.5353],
        [0.1505, 0.2355, 0.8935]])
Нормальное распределение: 
tensor([[-0.4856, -0.5720, -1.2620],
        [ 0.2153,  0.5650,  0.7954]])
Распределение Бернулли: 
tensor([[0., 1., 0.],
        [0., 1., 1.]])


In [15]:
# изменение размерностей view = np.reshape
b, b.stride()

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 (3, 1))

In [16]:
b.view(3, 2), b.view(3, 2).stride()

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.]]),
 (2, 1))

In [17]:
b.view(-1), b  # не изменяет исходный тензор

(tensor([1., 2., 3., 4., 5., 6.]),
 tensor([[1., 2., 3.],
         [4., 5., 6.]]))

In [18]:
b.reshape(-1)  # упорядоченная в памяти копия

tensor([1., 2., 3., 4., 5., 6.])

In [19]:
# изменение типа тензоров
# type_as не изменяет сходный тензор!
a = torch.FloatTensor([1.5, 3.2, -7])
a.type_as(torch.IntTensor())

tensor([ 1,  3, -7], dtype=torch.int32)

In [20]:
a.to(torch.int32), a.to(torch.uint8)

(tensor([ 1,  3, -7], dtype=torch.int32),
 tensor([  1,   3, 249], dtype=torch.uint8))

In [21]:
# арифметические операции
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [22]:
print(a + b)  # == a.add(b)
print(a - b)  # == a.sub(b) -копия; a.sub_(b) -inplace
print(a * b)  # == a.mul(b)
print(a / b)  # == a.div(b)

tensor([[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [200., 400., 600.]])
tensor([[ 2.,  4.,  6.],
        [20., 40., 60.],
        [ 0.,  0.,  0.]])
tensor([[-1.0000e+00, -4.0000e+00, -9.0000e+00],
        [-1.0000e+02, -4.0000e+02, -9.0000e+02],
        [ 1.0000e+04,  4.0000e+04,  9.0000e+04]])
tensor([[-1., -1., -1.],
        [-1., -1., -1.],
        [ 1.,  1.,  1.]])


In [23]:
# сравнение тензоров
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])
a == b

tensor([[False, False, False],
        [False, False, False],
        [ True,  True,  True]])

In [24]:
# прочие мат операции
a.sin()  # a.tan(), a.exp(), a.log(), a.abs()...

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.5440,  0.9129, -0.9880],
        [-0.5064, -0.8733, -0.9998]])

In [25]:
# функции агрегации
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [26]:
a.sum(dim=1)  # суммируется строка

tensor([  6.,  60., 600.])

In [27]:
a.sum(0)

tensor([111., 222., 333.])

In [28]:
a.max()  # по всему тензору // a.min()

tensor(300.)

## Матричные операции

In [29]:
a.t()  # Transpose a tensor

tensor([[  1.,  10., 100.],
        [  2.,  20., 200.],
        [  3.,  30., 300.]])

In [30]:
# векторное (скалярное) произведение
a = torch.FloatTensor([1, 2, 3, 4, 5, 6])
b = torch.FloatTensor([-1, -2, -4, -6, -8, -10])
a.dot(b)

tensor(-141.)

In [31]:
a @ b  # = a.dot(b)

tensor(-141.)

In [32]:
# матричное произведение
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [33]:
a.mm(b)  # = a @ b

tensor([[  279.,   558.,   837.],
        [ 2790.,  5580.,  8370.],
        [27900., 55800., 83700.]])

In [34]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1], [-10], [100]])

In [35]:
a @ b

tensor([[  279.],
        [ 2790.],
        [27900.]])

In [36]:
# умножение матрицы на вектор
a @ b.view(-1), b.view(-1)

(tensor([  279.,  2790., 27900.]), tensor([ -1., -10., 100.]))

In [37]:
a.mv(b.view(-1))

tensor([  279.,  2790., 27900.])

## NUMPY <--> PYTORCH

In [38]:
a = np.random.rand(3, 3)
a, type(a)

(array([[0.65462221, 0.23890459, 0.99863569],
        [0.2893298 , 0.63769945, 0.94513553],
        [0.75678708, 0.10639604, 0.45744498]]),
 numpy.ndarray)

In [39]:
# numpy->pytorch
# используют одну и ту же память - если изменить а, то изменится и b
b = torch.from_numpy(a)
b

tensor([[0.6546, 0.2389, 0.9986],
        [0.2893, 0.6377, 0.9451],
        [0.7568, 0.1064, 0.4574]], dtype=torch.float64)

In [40]:
a = torch.FloatTensor(2, 3, 4)
a, type(a)

(tensor([[[1.0564e-05, 4.1880e-11, 4.2490e-05, 2.9573e-18],
          [6.7333e+22, 1.7591e+22, 1.7184e+25, 4.3222e+27],
          [6.1972e-04, 7.2443e+22, 1.7728e+28, 7.0367e+22]],
 
         [[9.6695e-06, 8.3101e+20, 1.3028e-11, 1.7186e-04],
          [1.0489e-08, 8.1919e-10, 1.9968e+20, 1.1038e-05],
          [3.3209e-09, 3.1199e-18, 7.7052e+31, 1.9447e+31]]]),
 torch.Tensor)

In [41]:
x = a.numpy()
x, type(x)

(array([[[1.05635709e-05, 4.18795901e-11, 4.24899226e-05, 2.95732103e-18],
         [6.73331199e+22, 1.75905377e+22, 1.71842178e+25, 4.32216629e+27],
         [6.19715371e-04, 7.24431922e+22, 1.77283446e+28, 7.03667221e+22]],
 
        [[9.66948755e-06, 8.31008144e+20, 1.30278895e-11, 1.71855820e-04],
         [1.04892424e-08, 8.19187829e-10, 1.99682342e+20, 1.10381270e-05],
         [3.32091865e-09, 3.11990731e-18, 7.70520767e+31, 1.94469173e+31]]],
       dtype=float32),
 numpy.ndarray)

In [42]:
a.zero_()
a, x

(tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]),
 array([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],
 
        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]], dtype=float32))