# BASE OPERATIONS

In [1]:
import torch
import numpy as np

*************************

In [2]:
# Создайте случайный FloatTensor размера 3x4x5
x = torch.FloatTensor(3, 4, 5)
print(x)

tensor([[[3.6880e+22, 7.8893e-43, 5.5821e-37, 1.6115e-43, 0.0000e+00],
         [0.0000e+00, 2.1019e-44, 0.0000e+00, 2.7988e+22, 7.8893e-43],
         [8.4187e+22, 7.8893e-43, 0.0000e+00, 0.0000e+00, 2.1019e-44],
         [0.0000e+00, 1.0996e+22, 7.8893e-43, 8.4187e+22, 7.8893e-43]],

        [[0.0000e+00, 0.0000e+00, 2.1019e-44, 0.0000e+00, 2.8872e+22],
         [7.8893e-43, 8.4187e+22, 7.8893e-43, 0.0000e+00, 0.0000e+00],
         [2.1019e-44, 0.0000e+00, 8.1830e+18, 7.8893e-43, 8.4187e+22],
         [7.8893e-43, 0.0000e+00, 0.0000e+00, 2.1019e-44, 0.0000e+00]],

        [[3.6828e+22, 7.8893e-43, 8.4187e+22, 7.8893e-43, 0.0000e+00],
         [0.0000e+00, 2.1019e-44, 0.0000e+00, 3.6455e+22, 7.8893e-43],
         [8.4187e+22, 7.8893e-43, 0.0000e+00, 0.0000e+00, 2.1019e-44],
         [0.0000e+00, 1.2041e+22, 7.8893e-43, 8.4187e+22, 7.8893e-43]]])


In [3]:
# Выведите его форму (shape)
x.shape, x.size()

(torch.Size([3, 4, 5]), torch.Size([3, 4, 5]))

In [4]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
b = torch.CharTensor([1, 4, 2, 2, 1])
x * b

tensor([[[3.6880e+22, 3.1557e-42, 1.1164e-36, 3.2230e-43, 0.0000e+00],
         [0.0000e+00, 8.4078e-44, 0.0000e+00, 5.5975e+22, 7.8893e-43],
         [8.4187e+22, 3.1557e-42, 0.0000e+00, 0.0000e+00, 2.1019e-44],
         [0.0000e+00, 4.3983e+22, 1.5779e-42, 1.6837e+23, 7.8893e-43]],

        [[0.0000e+00, 0.0000e+00, 4.2039e-44, 0.0000e+00, 2.8872e+22],
         [7.8893e-43, 3.3675e+23, 1.5779e-42, 0.0000e+00, 0.0000e+00],
         [2.1019e-44, 0.0000e+00, 1.6366e+19, 1.5779e-42, 8.4187e+22],
         [7.8893e-43, 0.0000e+00, 0.0000e+00, 4.2039e-44, 0.0000e+00]],

        [[3.6828e+22, 3.1557e-42, 1.6837e+23, 1.5779e-42, 0.0000e+00],
         [0.0000e+00, 8.4078e-44, 0.0000e+00, 7.2911e+22, 7.8893e-43],
         [8.4187e+22, 3.1557e-42, 0.0000e+00, 0.0000e+00, 2.1019e-44],
         [0.0000e+00, 4.8162e+22, 1.5779e-42, 1.6837e+23, 7.8893e-43]]])

In [5]:
# Приведите его к форме 6 X 10
x = x.view(6, 10)

In [6]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
z = x.mm(x.T)
z.size()

torch.Size([6, 6])

In [7]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

from torch.autograd import Variable

x = Variable(torch.ones(3), requires_grad=True)
z = Variable(torch.ones(3), requires_grad=True)
t = Variable(torch.ones(3), requires_grad=True)
point = torch.FloatTensor([1, 0.5, 2])
y = x**3 + z - 75*t

y.backward(point)
print(x.grad, z.grad, t.grad, sep='\n')

tensor([3.0000, 1.5000, 6.0000])
tensor([1.0000, 0.5000, 2.0000])
tensor([ -75.0000,  -37.5000, -150.0000])


In [8]:
# Создайте единичный тензор размера 5x6
x = torch.ones(5, 6)
x

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [9]:
# Переведите его в формат numpy
x = x.numpy()
x, type(x)

(array([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]], dtype=float32),
 numpy.ndarray)

## тензоры pytorch

* **torch.HalfTensor** = 16 бит, floating point
* **torch.FloatTensor**  = 32 бита, floating point
* **torch.DoubleTensor**  =    64 бита, floating point
* **torch.ShortTensor**    =   16 бит, integer, signed
* **torch.IntTensor**      =   32 бита, integer, signed
* **torch.LongTensor**   =      64 бита, integer, signed

* **torch.CharTensor**    =  8 бит, integer, signed
* **torch.ByteTensor**     = 8 бит, integer, unsigned

In [10]:
# Создание тензора
a = torch.FloatTensor([1, 2])
b = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])

print(a, a.shape)
print(b, b.shape)

tensor([1., 2.]) torch.Size([2])
tensor([[1., 2., 3.],
        [4., 5., 6.]]) torch.Size([2, 3])


In [11]:
# создание тензора по размерам (заполнен случайными величинами (мусором))
x = torch.FloatTensor(2, 3, 4)
print(x, x.shape)

tensor([[[1.7753e+28, 1.3458e-14, 2.4754e-12, 7.8451e+17],
         [7.5553e+28, 5.2839e-11, 7.3908e+22, 8.0324e+17],
         [7.5539e+31, 7.5338e+28, 6.1687e+16, 1.4584e-19]],

        [[1.4584e-19, 3.1432e-12, 1.3589e-19, 1.3563e-19],
         [2.0408e-07, 5.9669e-07, 2.3868e-06, 4.9153e-14],
         [4.7429e+30, 7.4908e+11, 1.2739e-14, 1.4586e-19]]]) torch.Size([2, 3, 4])


In [12]:
x = torch.IntTensor(3, 3, 4)
print(x, x.shape)

tensor([[[1615009696,        563, 1615009696,        563],
         [1680889264,        563, 1680889264,        563],
         [1614282352,        563, 1614902624,        563]],

        [[1614280048,        563, 1614280048,        563],
         [  71357200,        563,   71357200,        563],
         [1680890288,        563, 1615010528,        563]],

        [[1613756368,        563, 1613756368,        563],
         [  71350160,        563,   71350160,        563],
         [1614280048,        563, 1614280048,        563]]], dtype=torch.int32) torch.Size([3, 3, 4])


In [13]:
# заполнение 0
x1 = torch.FloatTensor(3, 2, 4)
x1.zero_()
x2 = torch.zeros(3, 2, 4)
x3 = torch.zeros_like(x1)

assert torch.allclose(x1, x2) and torch.allclose(x1, x3)
x1

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [14]:
# случайные распределения

x = torch.randn((2, 3))
print('Стандартное Нормальное распределение: ', x, sep='\n')
x.random_(0, 10)
print('Дискретное распределение: ', x, sep='\n')
x.uniform_(0, 1)
print('Равномерное распределение: ', x, sep='\n')
x.normal_(mean=0, std=1)
print('Нормальное распределение: ', x, sep='\n')
x.bernoulli_(p=0.5)
print('Распределение Бернулли: ', x, sep='\n')

Стандартное Нормальное распределение: 
tensor([[ 0.7059, -0.4422, -0.8414],
        [-0.3493,  0.2140,  1.4796]])
Дискретное распределение: 
tensor([[2., 4., 9.],
        [2., 5., 8.]])
Равномерное распределение: 
tensor([[0.3343, 0.2149, 0.9634],
        [0.2517, 0.0586, 0.1906]])
Нормальное распределение: 
tensor([[-0.1127,  0.5058, -0.0687],
        [ 0.4541, -1.5531, -0.3590]])
Распределение Бернулли: 
tensor([[0., 1., 0.],
        [1., 0., 1.]])


In [15]:
# изменение размерностей view = np.reshape
b, b.stride()

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 (3, 1))

In [16]:
b.view(3, 2), b.view(3, 2).stride()

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.]]),
 (2, 1))

In [17]:
b.view(-1), b  # не изменяет исходный тензор

(tensor([1., 2., 3., 4., 5., 6.]),
 tensor([[1., 2., 3.],
         [4., 5., 6.]]))

In [18]:
b.reshape(-1)  # упорядоченная в памяти копия

tensor([1., 2., 3., 4., 5., 6.])

In [19]:
# изменение типа тензоров
# type_as не изменяет сходный тензор!
a = torch.FloatTensor([1.5, 3.2, -7])
a.type_as(torch.IntTensor())

tensor([ 1,  3, -7], dtype=torch.int32)

In [20]:
a.to(torch.int32), a.to(torch.uint8)

(tensor([ 1,  3, -7], dtype=torch.int32),
 tensor([  1,   3, 249], dtype=torch.uint8))

In [21]:
# арифметические операции
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [22]:
print(a + b)  # == a.add(b)
print(a - b)  # == a.sub(b) -копия; a.sub_(b) -inplace
print(a * b)  # == a.mul(b)
print(a / b)  # == a.div(b)

tensor([[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [200., 400., 600.]])
tensor([[ 2.,  4.,  6.],
        [20., 40., 60.],
        [ 0.,  0.,  0.]])
tensor([[-1.0000e+00, -4.0000e+00, -9.0000e+00],
        [-1.0000e+02, -4.0000e+02, -9.0000e+02],
        [ 1.0000e+04,  4.0000e+04,  9.0000e+04]])
tensor([[-1., -1., -1.],
        [-1., -1., -1.],
        [ 1.,  1.,  1.]])


In [23]:
# сравнение тензоров
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])
a == b

tensor([[False, False, False],
        [False, False, False],
        [ True,  True,  True]])

In [24]:
# прочие мат операции
a.sin()  # a.tan(), a.exp(), a.log(), a.abs()...

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.5440,  0.9129, -0.9880],
        [-0.5064, -0.8733, -0.9998]])

In [25]:
# функции агрегации
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [26]:
a.sum(dim=1)  # суммируется строка

tensor([  6.,  60., 600.])

In [27]:
a.sum(0)

tensor([111., 222., 333.])

In [28]:
a.max()  # по всему тензору // a.min()

tensor(300.)

## Матричные операции

In [29]:
a.t()  # Transpose a tensor

tensor([[  1.,  10., 100.],
        [  2.,  20., 200.],
        [  3.,  30., 300.]])

In [30]:
# векторное (скалярное) произведение
a = torch.FloatTensor([1, 2, 3, 4, 5, 6])
b = torch.FloatTensor([-1, -2, -4, -6, -8, -10])
a.dot(b)

tensor(-141.)

In [31]:
a @ b  # = a.dot(b)

tensor(-141.)

In [32]:
# матричное произведение
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [33]:
a.mm(b)  # = a @ b

tensor([[  279.,   558.,   837.],
        [ 2790.,  5580.,  8370.],
        [27900., 55800., 83700.]])

In [34]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1], [-10], [100]])

In [35]:
a @ b

tensor([[  279.],
        [ 2790.],
        [27900.]])

In [36]:
# умножение матрицы на вектор
a @ b.view(-1), b.view(-1)

(tensor([  279.,  2790., 27900.]), tensor([ -1., -10., 100.]))

In [37]:
a.mv(b.view(-1))

tensor([  279.,  2790., 27900.])

## NUMPY <--> PYTORCH

In [38]:
a = np.random.rand(3, 3)
a, type(a)

(array([[0.49035856, 0.65663536, 0.92820379],
        [0.50335463, 0.99131842, 0.9889529 ],
        [0.04866556, 0.51402523, 0.3560609 ]]),
 numpy.ndarray)

In [39]:
# numpy->pytorch
# используют одну и ту же память - если изменить а, то изменится и b
b = torch.from_numpy(a)
b

tensor([[0.4904, 0.6566, 0.9282],
        [0.5034, 0.9913, 0.9890],
        [0.0487, 0.5140, 0.3561]], dtype=torch.float64)

In [40]:
a = torch.FloatTensor(2, 3, 4)
a, type(a)

(tensor([[[2.7005e-06, 4.0743e-11, 4.3125e-08, 2.9575e-18],
          [6.7333e+22, 1.7591e+22, 1.7184e+25, 4.3222e+27],
          [6.1972e-04, 7.2443e+22, 1.7728e+28, 7.0367e+22]],
 
         [[2.3607e-09, 6.4472e-10, 1.0368e-11, 1.0780e-08],
          [1.6783e-07, 2.5961e+20, 1.0325e-05, 1.0385e+21],
          [1.3423e-05, 2.4041e-18, 7.7052e+31, 1.9447e+31]]]),
 torch.Tensor)

In [41]:
x = a.numpy()
x, type(x)

(array([[[2.7004976e-06, 4.0742722e-11, 4.3124775e-08, 2.9574803e-18],
         [6.7333120e+22, 1.7590538e+22, 1.7184218e+25, 4.3221663e+27],
         [6.1971537e-04, 7.2443192e+22, 1.7728345e+28, 7.0366722e+22]],
 
        [[2.3607147e-09, 6.4472111e-10, 1.0367571e-11, 1.0779874e-08],
         [1.6782788e-07, 2.5961100e+20, 1.0324924e-05, 1.0385190e+21],
         [1.3423432e-05, 2.4041121e-18, 7.7052077e+31, 1.9446917e+31]]],
       dtype=float32),
 numpy.ndarray)

In [42]:
a.zero_()
a, x

(tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]),
 array([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],
 
        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]], dtype=float32))