# BASE OPERATIONS

In [1]:
import torch
import numpy as np

In [2]:
# тензоры pytorch
torch.HalfTensor      # 16 бит, floating point
torch.FloatTensor     # 32 бита, floating point
torch.DoubleTensor    # 64 бита, floating point

torch.ShortTensor     # 16 бит, integer, signed
torch.IntTensor       # 32 бита, integer, signed
torch.LongTensor      # 64 бита, integer, signed

torch.CharTensor      # 8 бит, integer, signed
torch.ByteTensor      # 8 бит, integer, unsigned

torch.ByteTensor

In [3]:
# Создание тензора
a = torch.FloatTensor([1, 2])
b = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])

print(a, a.shape)
print(b, b.shape)

tensor([1., 2.]) torch.Size([2])
tensor([[1., 2., 3.],
        [4., 5., 6.]]) torch.Size([2, 3])


In [4]:
# создание тензора по размерам (заполнен случайными величинами (мусором))
x = torch.FloatTensor(2, 3, 4)
print(x, x.shape)

tensor([[[2.5226e-18, 2.5930e-09, 1.0356e-11, 3.0883e-09],
         [1.6806e-04, 4.0747e-11, 1.0431e-08, 2.9572e-18],
         [6.7333e+22, 1.7591e+22, 1.7184e+25, 4.3222e+27]],

        [[6.1972e-04, 7.2443e+22, 1.7728e+28, 7.0367e+22],
         [1.5109e-07, 2.0662e+20, 1.2858e-11, 1.3293e-08],
         [1.0780e-08, 3.2913e-09, 1.0324e-05, 5.3481e+22]]]) torch.Size([2, 3, 4])


In [5]:
x = torch.IntTensor(3, 3, 4)
print(x, x.shape)

tensor([[[4259917, 6029390, 7209057, 6488161],
         [7209071, 6357092, 6029363, 6881388],
         [6029410, 6881395, 6619252, 7340077]],

        [[6488161, 6357099, 6619239, 6029427],
         [7274612, 6488178, 6029416, 7667821],
         [7602284, 7340137, 7274610, 6619235]],

        [[7536755, 7209065, 6029415, 6226015],
         [7929968, 6357091, 6815843, 6226021],
         [6029407, 6357087, 6684788, 7471215]]], dtype=torch.int32) torch.Size([3, 3, 4])


In [6]:
# заполнение 0
x1 = torch.FloatTensor(3, 2, 4)
x1.zero_()
x2 = torch.zeros(3, 2, 4)
x3 = torch.zeros_like(x1)

assert torch.allclose(x1, x2) and torch.allclose(x1, x3)
x1

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
# случайные распределения

x = torch.randn((2, 3))
print('Стандартное Нормальное распределение: ', x, sep='\n')
x.random_(0, 10)
print('Дискретное распределение: ', x, sep='\n')
x.uniform_(0, 1)
print('Равномерное распределение: ', x, sep='\n')
x.normal_(mean=0, std=1)
print('Нормальное распределение: ', x, sep='\n')
x.bernoulli_(p=0.5)
print('Распределение Бернулли: ', x, sep='\n')

Стандартное Нормальное распределение: 
tensor([[-1.4923,  0.4991, -0.8757],
        [ 0.3798, -1.0812,  0.3151]])
Дискретное распределение: 
tensor([[8., 3., 0.],
        [3., 5., 0.]])
Равномерное распределение: 
tensor([[0.3946, 0.7799, 0.3997],
        [0.5317, 0.8093, 0.7354]])
Нормальное распределение: 
tensor([[-0.3220, -0.0956, -0.8434],
        [-1.1891,  0.0841,  0.2941]])
Распределение Бернулли: 
tensor([[0., 1., 0.],
        [0., 1., 0.]])


In [8]:
# изменение размерностей view = np.reshape
b, b.stride()

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 (3, 1))

In [9]:
b.view(3, 2), b.view(3, 2).stride()

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.]]),
 (2, 1))

In [10]:
b.view(-1), b  # не изменяет исходный тензор

(tensor([1., 2., 3., 4., 5., 6.]),
 tensor([[1., 2., 3.],
         [4., 5., 6.]]))

In [11]:
b.reshape(-1)  # упорядоченная в памяти копия

tensor([1., 2., 3., 4., 5., 6.])

In [12]:
# изменение типа тензоров
# type_as не изменяет сходный тензор!
a = torch.FloatTensor([1.5, 3.2, -7])
a.type_as(torch.IntTensor())

tensor([ 1,  3, -7], dtype=torch.int32)

In [13]:
a.to(torch.int32), a.to(torch.uint8)

(tensor([ 1,  3, -7], dtype=torch.int32),
 tensor([  1,   3, 249], dtype=torch.uint8))

In [14]:
# арифметические операции
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [15]:
print(a + b)  # == a.add(b)
print(a - b)  # == a.sub(b) -копия; a.sub_(b) -inplace
print(a * b)  # == a.mul(b)
print(a / b)  # == a.div(b)

tensor([[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [200., 400., 600.]])
tensor([[ 2.,  4.,  6.],
        [20., 40., 60.],
        [ 0.,  0.,  0.]])
tensor([[-1.0000e+00, -4.0000e+00, -9.0000e+00],
        [-1.0000e+02, -4.0000e+02, -9.0000e+02],
        [ 1.0000e+04,  4.0000e+04,  9.0000e+04]])
tensor([[-1., -1., -1.],
        [-1., -1., -1.],
        [ 1.,  1.,  1.]])


In [16]:
# сравнение тензоров
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])
a == b

tensor([[False, False, False],
        [False, False, False],
        [ True,  True,  True]])

In [17]:
# прочие мат операции
a.sin()  # a.tan(), a.exp(), a.log(), a.abs()...

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.5440,  0.9129, -0.9880],
        [-0.5064, -0.8733, -0.9998]])

In [18]:
# функции агрегации
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [19]:
a.sum(dim=1)  # суммируется строка

tensor([  6.,  60., 600.])

In [20]:
a.sum(0)

tensor([111., 222., 333.])

In [21]:
a.max()  # по всему тензору // a.min()

tensor(300.)

## Матричные операции

In [22]:
a.t()  # Transpose a tensor

tensor([[  1.,  10., 100.],
        [  2.,  20., 200.],
        [  3.,  30., 300.]])

In [23]:
# векторное (скалярное) произведение
a = torch.FloatTensor([1, 2, 3, 4, 5, 6])
b = torch.FloatTensor([-1, -2, -4, -6, -8, -10])
a.dot(b)

tensor(-141.)

In [24]:
a @ b  # = a.dot(b)

tensor(-141.)

In [25]:
# матричное произведение
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [26]:
a.mm(b)  # = a @ b

tensor([[  279.,   558.,   837.],
        [ 2790.,  5580.,  8370.],
        [27900., 55800., 83700.]])

In [27]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1], [-10], [100]])

In [28]:
a @ b

tensor([[  279.],
        [ 2790.],
        [27900.]])

In [29]:
# умножение матрицы на вектор
a @ b.view(-1), b.view(-1)

(tensor([  279.,  2790., 27900.]), tensor([ -1., -10., 100.]))

In [30]:
a.mv(b.view(-1))

tensor([  279.,  2790., 27900.])

## NUMPY <--> PYTORCH

In [31]:
a = np.random.rand(3, 3)
a, type(a)

(array([[0.96505741, 0.75624687, 0.40913288],
        [0.96734235, 0.81378323, 0.84521941],
        [0.29674017, 0.71722953, 0.87839594]]),
 numpy.ndarray)

In [32]:
# numpy->pytorch
# используют одну и ту же память - если изменить а, то изменится и b
b = torch.from_numpy(a)
b

tensor([[0.9651, 0.7562, 0.4091],
        [0.9673, 0.8138, 0.8452],
        [0.2967, 0.7172, 0.8784]], dtype=torch.float64)

In [36]:
a = torch.FloatTensor(2, 3, 4)
a, type(a)

tensor([[[0.0000e+00, 4.4842e-44, 7.7052e+31, 7.2148e+22],
         [2.5226e-18, 2.5930e-09, 1.0356e-11, 3.0883e-09],
         [6.4475e-10, 4.2107e-11, 4.2961e-05, 2.9574e-18]],

        [[6.7333e+22, 1.7591e+22, 1.7184e+25, 4.3222e+27],
         [6.1972e-04, 7.2443e+22, 1.7728e+28, 7.0367e+22],
         [1.5109e-07, 2.0662e+20, 1.2858e-11, 1.3293e-08]]])

In [34]:
x = a.numpy()
x, type(x)

(array([[[1.68063474e-04, 4.09745363e-11, 2.59349231e-09, 2.95716221e-18],
         [6.73331199e+22, 1.75905377e+22, 1.71842178e+25, 4.32216629e+27],
         [6.19715371e-04, 7.24431922e+22, 1.77283446e+28, 7.03667221e+22]],
 
        [[1.51085743e-07, 2.06617146e+20, 1.28579855e-11, 1.32934481e-08],
         [1.07802807e-08, 3.29130190e-09, 1.03242664e-05, 5.34807905e+22],
         [2.58121347e-09, 3.05218913e-18, 7.70520767e+31, 1.94469173e+31]]],
       dtype=float32),
 numpy.ndarray)

In [35]:
a.zero_()
a, x

(tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]),
 array([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],
 
        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]], dtype=float32))